### ISSUE TITLE
User gets "Internal Server Error" 500 frequently

### ISSUE THREAD

**Issue by Tamara-Supernova** [Supernova-Studio/sdk-typescript#16]
**ISSUE**

"This morning, our team tried to log into Supernova. However, the server's response gradually became slower and we saw an error like this eventually.
It should be noted that this happened quite frequently in the early morning (our time, GMT+9, from 8:30 AM to 11:30 AM) and sometimes affect our work significantly.
Could you please kindly give this error a check (we know that this has to deal with the hosting servers)? It would be super helpful if we can have this issue solved."

![Screenshot_2022-06-13_at_11.10.03.png](https://images.zenhubusercontent.com/62a1bfda7c8ae7978fd95f66/09770142-cd7c-4c72-bbaa-f0b307f8afca)SSUE

Workspace URL  cloud.supernova.io/ws/zooom 
Email japan@zooom.com

**Comment by Tamara-Supernova** [comment]
Please ignore, this was created wrongly

**Comment by Ydus** [comment]
@Tamara-Supernova can I delete this? 🙂
