### ISSUE TITLE
Cannot read properties of undefined (reading 'referencedToken')

### ISSUE THREAD

**Issue by coolbaluk** [Supernova-Studio/sdk-typescript#32]
👋 This looks like a great tool!

I'm trying to use the client to ingest our tokens, but running into this error:

>----- Loaded token data:
Nodes: 337
Sets: 3,   
| base: 141 nodes, 
| ThemeMS: 98 nodes,  
| ThemeWF: 98 nodes 
Themes: 0,      
TypeError: Cannot read properties of undefined (reading 'referencedToken')

The tokens that error out reference other tokens in this format:

> "Title": {
      "H1": {
        "value": {
          "fontFamily": "{fontFamilies.heading}",
          "fontWeight": "{fontWeight.bold}",
          "lineHeight": "floor({fontSize.10}+{lineHeight.default})",
          "fontSize": "{fontSize.10}",
          "letterSpacing": "{letterSpacing.00}",
          "paragraphSpacing": "{paragraphSpacing.none}",
          "paragraphIndent": "{paragraphIndent.0}",
          "textCase": "{textCase.none}",
          "textDecoration": "{textDecoration.none}"
        },
        "type": "typography"
      }
}

Any suggestions on how to proceed ? Do I need to do a transformation before ingesting ?

**Comment by JiriTrecak** [comment]
Hey @coolbaluk , could you please send out your token file (if possible) that fails to import to jiri [at] supernova [dot] io? :) Of course, you can attach it as well if it can be public. We'll use it for testing and fixing!

**Comment by coolbaluk** [comment]
[Archive.zip](https://github.com/Supernova-Studio/sdk-typescript/files/10458038/Archive.zip)

Here it is, nothing confidential in there. Also attached the supernova config.

Thanks and keep me in the loop!

**Comment by JiriTrecak** [comment]
Thank you, we'll try to fix it as soon as possible 👍🏻 And thanks for the kind words about Supernova, that means a lot!

**Comment by coolbaluk** [comment]
Looks like the new client version has solved this!

It also let me import the radii that the direct figma import was failing to, great work

Closing this one
